# Generated by Django 4.2.8 on 2024-01-03 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_boardcomment_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.board'),
        ),
    ]
