# Generated by Django 4.2.8 on 2024-01-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_boardchildcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardchildcomment',
            name='comment',
        ),
    ]
