# Generated by Django 4.2.8 on 2024-01-03 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_comment_boardchildcomment_child_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardchildcomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='api.boardcomment'),
        ),
    ]
