# Generated by Django 4.2.8 on 2024-01-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_boardchildcomment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardchildcomment',
            old_name='comment',
            new_name='parent_comment',
        ),
    ]
