# Generated by Django 4.2.8 on 2024-01-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_comment_boardchildcomment_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardchildcomment',
            old_name='parent_comment',
            new_name='p_comment',
        ),
    ]
