# Generated by Django 4.2.8 on 2024-01-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_parent_comment_boardchildcomment_p_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardchildcomment',
            old_name='child_comment',
            new_name='comment',
        ),
    ]
