# Generated by Django 4.2.8 on 2024-01-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_child_comment_boardchildcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
