# Generated by Django 4.2.8 on 2024-01-07 14:22

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.hashed_upload_to),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.hashed_upload_to)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.board')),
            ],
        ),
    ]
