# Generated by Django 4.2.8 on 2024-01-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_board_images_alter_image_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
    ]
