# Generated by Django 4.2.8 on 2024-01-09 01:00

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_board_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.hashed_upload_to)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_images', to='api.boardcomment')),
            ],
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='comment_images', to='api.commentimage'),
        ),
    ]
